hufscheer/spectator-server

src/main/java/com/sports/server/comment/domain/Comment.java, src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java, src/main/java/com/sports/server/comment/dto/response/CommentResponseDto.java
=> [REFACTOR] 경기의 댓글을 반환할 때 댓글의 id 를 반환하도록 한다.

src/main/java/com/sports/server/comment/domain/Comment.java, src/main/java/com/sports/server/comment/dto/CommentValidatorMessages.java, src/main/java/com/sports/server/comment/dto/request/CommentRequestDto.java, src/main/java/com/sports/server/common/ValidatorMessages.java, src/main/java/com/sports/server/game/domain/Game.java, src/main/java/com/sports/server/game/domain/GameTeam.java, src/main/java/com/sports/server/game/domain/GameTeamPlayer.java, src/main/java/com/sports/server/league/domain/League.java, src/main/java/com/sports/server/league/domain/LeagueSport.java, src/main/java/com/sports/server/member/domain/Member.java, src/main/java/com/sports/server/organization/domain/Organization.java, src/main/java/com/sports/server/record/domain/Record.java, src/main/java/com/sports/server/report/domain/Report.java, src/main/java/com/sports/server/sport/domain/Quarter.java, src/main/java/com/sports/server/sport/domain/Sport.java, src/main/java/com/sports/server/team/domain/Team.java
- closed #36 
- erd 수정에 따른 엔티티 일부 수정
- league 패키지 추가 및 LeagueSport 는 league 에 속하도록 했어요.
- 유효성 검사 메시지는 현재 쓰이는 부분이 comment 밖에 없어서, 일단은 CommentValidatorMessages 만 추가해뒀어요!
이 두가지에 대해서 피드백 부탁드립니당.!
=> [REFACTOR] 유효성 검사 메시지 도메인에 종속되도록 수정 및 엔티티 수정

src/main/java/com/sports/server/common/config/WebConfig.java
=> [CHORE] 클라이언트 배포 서버 url 수정

build.gradle, src/main/resources/application.yaml
- #88 
- 다른 레포에서 더 추가해야할 작업이 있어서 이슈는 닫지 않습니다.
- 프로메테우스 의존성 추가
- 아마 패키지 리팩터링한거랑 충돌하지는 않을거고 하더라도 이 PR에선 2개 파일만 건드려서 충돌 해결하기 쉬울 것 같아요! 확인할게 없어서 바로 확인해주시면 머지하고 다음 단계 진행하려구요
=> [CHORE] 프로메테우스 설정 추가

src/main/resources/db/migration/V2__update-table.sql
=> [FIX] 마이그레이션 파일 v2 수정

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/query/application/LeagueQueryService.java, src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java, src/main/java/com/sports/server/query/presentation/LeagueQueryController.java, src/main/java/com/sports/server/query/repository/LeagueTeamQueryRepository.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java, src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java, src/test/resources/league-fixture.sql
- closed #112 
- 리그에 참여하는 리그팀 전체 조회 기능
=> [FEAT] 리그팀 전체 조회 기능 구현

.github/workflows/cd.yml, src/main/java/com/sports/server/query/dto/response/GameResponseDto.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java, src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
- closed #125 
- Github Action 배포 스크립트에 타임존 설정 추가
- 혹시 깃헛 액션을 돌리는 서버 시간이 안맞아서 발생하는 문제인가 싶어서 추가해봤는데 빌드 잘 되는거 확인했습니다
``` yml
- name: 타임존 설정
uses: szenius/set-timezone@v1.2
with:
timezoneLinux: "Asia/Seoul"
```
- 게임 목록 조회에서 round 정보가 빠져 있고 클라이언트에서 요청하길래 추가해 두었습니다!
=> [FIX] 서버 시간 수정 후 빌드가 실패하는 문제 해결

src/main/java/com/sports/server/command/game/domain/LineupPlayer.java, src/main/resources/db/migration/V9__update-lineup-players.sql, src/test/resources/game-fixture.sql, src/test/resources/record-fixture.sql
- closed #135 
- lineup_players 와 league_team_players 가 간접 참조하도록 한다
=> [FEAT] lineup_players 와 league_team_players 가 간접 참조하도록 한다

src/main/java/com/sports/server/command/game/domain/GameTeam.java, src/main/java/com/sports/server/common/advice/ControllerExceptionAdvice.java, src/test/java/com/sports/server/command/game/application/GameLeagueTeamServiceTest.java
- closed #143 
- 음수일 경우 예외 발생
- customexception이 500 에러일 경우 로깅
=> [FIX] 응원 횟수 음수 방지 기능 구현

.gitignore, build.gradle, src/main/java/com/sports/server/command/game/domain/Game.java, src/main/java/com/sports/server/command/game/domain/GameTeam.java, src/main/java/com/sports/server/command/game/domain/LineupPlayer.java, src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java, src/main/java/com/sports/server/command/timeline/domain/ScoreTimeline.java, src/main/java/com/sports/server/command/timeline/domain/Timeline.java, src/test/java/com/sports/server/command/game/domain/GameTest.java, src/test/java/com/sports/server/command/timeline/domain/ReplacementTimelineTest.java, src/test/java/com/sports/server/command/timeline/domain/ScoreTimelineTest.java, src/test/java/com/sports/server/support/fixture/FixtureMonkeyUtils.java
- #161 
- 아직 api 구현까지는 하지 않아서 close 처리는 하지 않음
- 현제한테 api 문서 받고 이 로직을 api에 연결하는 PR을 따로 올릴 예정
- 교체 타임라인 생성 도메인 로직
- 득점 타임라인 생성 도메인 로직
- Game에 득점 기능 구현
- 저번에 얘기했던 대로 득점 타임라인이 생기면 Game에 득점했다는 메시지를 던져 게임 진행을 제어하도록 했습니다.
``` java
public static ScoreTimeline score(
Game game,
Quarter recordedQuarter,
Integer recordedAt,
LineupPlayer scorer,
Integer score
) {
game.score(scorer, score); // Game이 점수를 올리도록 메시지를 보냄
GameTeam team1 = game.getTeam1();
GameTeam team2 = game.getTeam2();
return new ScoreTimeline(
game,
recordedQuarter,
recordedAt,
scorer,
score,
team1,
team1.getScore(),
team2,
team2.getScore()
);
}
```
- 본격적으로 도메인 테스트를 작성하게 되면서 픽스처 생성이 어려웠고 매번 테스트 상황에 필요없는 값을 설정하기 번거로움
- 이를 해결하기 위해 도입
``` java
// Fixture Monkey를 더 편하게 사용하도록 util 클래스 작성
public class FixtureMonkeyUtils {
private static final …
```
=> [FEAT] 득점, 교체 타임라인 생성 도메인 로직 구현

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/auth/config/SecurityConfig.java, src/main/java/com/sports/server/command/leagueteam/application/LeagueTeamService.java, src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeam.java, src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamPlayerFixtureRepository.java, src/main/java/com/sports/server/command/leagueteam/domain/LeagueTeamRepository.java, src/main/java/com/sports/server/command/leagueteam/presentation/LeagueTeamController.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/leagueteam/acceptance/LeagueTeamAcceptanceTest.java, src/test/java/com/sports/server/command/leagueteam/application/LeagueTeamServiceTest.java, src/test/java/com/sports/server/command/leagueteam/presentation/LeagueTeamControllerTest.java
- closed #173 
- 리그팀 삭제
- 리그팀 로고 이미지 삭제
=> [FEAT] 리그팀 삭제

src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java, src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- closed #186 
- 인원수를 포함해서 반환하도록 수정
=> [FEAT] 리그팀에 인원수 표기하도록 수정

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/auth/config/SecurityConfig.java, src/main/java/com/sports/server/command/league/application/LeagueService.java, src/main/java/com/sports/server/command/league/domain/League.java, src/main/java/com/sports/server/command/league/domain/LeagueRepository.java, src/main/java/com/sports/server/command/league/presentation/LeagueController.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/league/acceptance/LeagueAcceptanceTest.java, src/test/java/com/sports/server/command/league/application/LeagueServiceTest.java, src/test/java/com/sports/server/command/league/domain/LeagueTest.java, src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
- closed #189
- 리그 삭제
- 논리 삭제를 위해 is_deleted 를 true 로 바꿨습니당
=> [FEAT] 리그 삭제

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/command/game/application/LineupPlayerService.java, src/main/java/com/sports/server/command/game/domain/Game.java, src/main/java/com/sports/server/command/game/domain/GameTeam.java, src/main/java/com/sports/server/command/game/domain/LineupPlayer.java, src/main/java/com/sports/server/command/game/presentation/GameController.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java, src/test/java/com/sports/server/command/game/application/LineupPlayerServiceTest.java, src/test/java/com/sports/server/command/game/domain/GameTeamTest.java, src/test/java/com/sports/server/command/game/domain/GameTest.java, src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java, src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java, src/test/resources/game-fixture.sql
- closed #203 
- 주장 등록
- 주장 취소
- 실수로 커밋 메시지에 #203인데 죄다 #200 을 붙였네요.. 다음부턴 조심할게요 ㅠ.ㅠ~~
=> [FEAT] 주장 등록 및 취소 기능 구현

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/command/game/domain/Game.java, src/main/java/com/sports/server/command/game/domain/GameTeam.java, src/main/java/com/sports/server/command/timeline/domain/PKTimeline.java, src/main/java/com/sports/server/command/timeline/dto/TimelineRequest.java, src/main/java/com/sports/server/command/timeline/mapper/TimelineMapper.java, src/main/java/com/sports/server/command/timeline/presentation/TimelineController.java, src/main/resources/db/migration/V18__update-game-teams.sql, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/game/domain/GameTest.java, src/test/java/com/sports/server/command/timeline/acceptance/TimelineAcceptanceTest.java, src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java, src/test/java/com/sports/server/command/timeline/presentation/TimelineControllerTest.java, src/test/resources/timeline-fixture.sql
- closed #236 
- 승부차기 타임라인 기능 구현
=> [FEAT] 승부차기 타임라인 등록 기능 구현

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/command/report/application/ReportService.java, src/main/java/com/sports/server/command/report/domain/Report.java, src/main/java/com/sports/server/command/report/domain/ReportRepository.java, src/main/java/com/sports/server/command/report/presentation/ReportController.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/report/acceptance/ReportAcceptanceTest.java, src/test/java/com/sports/server/command/report/application/ReportServiceTest.java, src/test/java/com/sports/server/command/report/presentation/ReportControllerTest.java, src/test/resources/report-fixture.sql
=> [FEAT] 응원톡 신고 무효처리 기능

src/main/java/com/sports/server/command/game/domain/Game.java, src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java, src/test/resources/timeline-fixture.sql
- #246 
- game의 isManagedBy 메소드의 오류 해결
=> [FIX] 게임 관련 권한 확인 제대로 되지 않던 문제 해결

src/docs/asciidoc/api.adoc, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
=> [DOCS] 누락된 주장 등록 및 해제 문서화 #254

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/command/game/domain/Game.java, src/main/java/com/sports/server/command/game/dto/GameRequestDto.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
- closed #253 
- 게임 등록 시 최근 추가 된 is_pk_taken 이 Null 로 들어가서 발생하는 오류 수정
=> [HOTFIX] 리그의 게임 조회에서 발생하는 오류 수정

src/main/java/com/sports/server/command/game/application/GameService.java, src/main/java/com/sports/server/command/game/presentation/GameController.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
- closed #252 
- 게임 등록 시 id 반환
- 문서화 수정
=> [REFACTOR] 게임 등록 시 ID 반환하도록 수정

src/main/java/com/sports/server/query/application/LeagueQueryService.java, src/main/java/com/sports/server/query/dto/response/LeagueResponseWithInProgressGames.java, src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
=> [FEAT] /leagues/manager 에 승부차기 성적 반환 안되는 오류 반영

src/test/java/com/sports/server/command/game/domain/GameTest.java
=> [TEST] 통과하지 못하는 테스트 수정

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/auth/config/SecurityConfig.java, src/main/java/com/sports/server/command/game/application/GameService.java, src/main/java/com/sports/server/command/game/domain/GameRepository.java, src/main/java/com/sports/server/command/game/presentation/GameController.java, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/game/acceptance/GameAcceptanceTest.java, src/test/java/com/sports/server/command/game/application/GameServiceTest.java, src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
=> [FEAT] 게임 삭제

.github/workflows/ci.yml, build.gradle, src/main/resources/application-ci.yml
=> [CHORE] ci 시 실패한 테스트만 expected, actual 출력하도록 수정

build.gradle
=> [FIX] 성공한 테스트들 불필요한 로그 출력하지 않도록 수정

.github/workflows/cd.yml
=> [CHORE] cd 시 타임존 설정 제거해보기..

src/main/java/com/sports/server/ServerApplication.java
=> [CHORE] ServerApplication.java에 있던 타임존 변경 설정 해제

src/main/resources/static/docs/api.html
=> [DOCS] 경고카드 타임라인 restDocs 업데이트

src/docs/asciidoc/api.adoc, src/main/java/com/sports/server/command/team/application/TeamService.java, src/main/java/com/sports/server/command/team/dto/TeamRequest.java, src/main/java/com/sports/server/command/team/presentation/TeamController.java, src/main/resources/application-ci.yml, src/main/resources/static/docs/api.html, src/test/java/com/sports/server/command/game/domain/GameTest.java, src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java, src/test/java/com/sports/server/command/team/acceptance/TeamAcceptanceTest.java, src/test/java/com/sports/server/command/team/presentation/TeamControllerTest.java
=> [REFACTOR] 팀 수정 요청에서 선수 필드 제거 및 문서 업데이트

Dockerfile
=> [CHORE] gc 로그 수집하지 않도록 수정
