- src/main/java/com/sports/server/game/application/GameService.java
- src/main/java/com/sports/server/game/domain/GameTeamRepository.java
- src/main/java/com/sports/server/game/dto/response/GameTeamCheerResponseDto.java
- src/main/java/com/sports/server/game/presentation/GameController.java
- closed #44 
- 경기의 아이디를 통해 경기에 참여하는 팀 전체를 찾는 메서드 repository에 추가 
- 경기의 아이디를 통해 응원 개수를 조회하는 기능 구현
- GameTeamService 를 따로 분리해야 했을까요? 분리할 정도의 사이즈가 아니라고 생각하기도 하고,, GameTeam 자체가 game 에 너무 종속적이라 어차피 경기 조회를 계속해서 해야 할 것 같아서 GameService 내부에 뒀는데 동규님의 의견은 어떠신지 궁금합니다 ! controller / service 는 Game와 GameTeam 을 분리하지 않았는데 repository 는 분리해서 어색한가 싶기도 하고,, 한편으로는 레포지토리가 entity 를 따라가니 당연한게 아닌가 싶기도 하고 그러네요! 
- 그때 이야기 나눴던 대로 dto 를 record 를 이용해봤어요! 우하하
- 단순한 궁금증인데요, record 를 사용하면 다른 클래스를 상속받지 못하는 것으로 알고 있는데 저희 화면의 특성상 dto 의 내용이 겹치는 경우가 많을 것으로 예상돼요. (ex. 경기 상세 조회에서의 경기 dto, 경기 목록 조회에서의 경기 dto) 이런 경우에는 선별해서 class 로 선언하는게 옳을까요?
> [FEAT] 응원하기 개수 확인 기능 구현

- build.gradle
- src/main/java/com/sports/server/league/application/LeagueService.java
- src/main/java/com/sports/server/league/domain/League.java
- src/main/java/com/sports/server/league/domain/LeagueRepository.java
- src/main/java/com/sports/server/league/domain/LeagueSport.java
- src/main/java/com/sports/server/league/domain/LeagueSportRepository.java
- src/main/java/com/sports/server/league/dto/response/LeagueResponse.java
- src/main/java/com/sports/server/league/dto/response/LeagueSportResponse.java
- src/main/java/com/sports/server/league/presentation/LeagueController.java
- src/main/java/com/sports/server/sport/domain/Sport.java
- src/test/java/com/sports/server/league/acceptance/LeagueAcceptanceTest.java
- src/test/java/com/sports/server/support/AcceptanceTest.java
- src/test/java/com/sports/server/support/isolation/DatabaseIsolation.java
- src/test/java/com/sports/server/support/isolation/DatabaseIsolationExtension.java
- src/test/java/com/sports/server/support/isolation/DatabaseManager.java
- src/test/resources/league-fixture.sql
closed #42 
closed #43 
- 리그 전체 조회 기능 구현
- 일단 response body에 리그 이름만 보내는데 더 필요한 정보가 있을까요?
- 정렬 조건은 시작일, 종료일 ASC로 구현했습니다.
- 리그 스포츠 조회 기능 구현
- 테스트 격리 환경 구성
- db를 사용하는 통합테스트에서 `@DatabaseIsolation`을 붙이면 테스트가 끝나고 데이터를 초기화하는 로직을 구현해 놓았습니다.
테스트 코드도 작성했습니다! 일단 E2E 테스트만 작성했어요. 테스트 코드를 어디까지 작성하면 좋을지에 대해서도 예기해보면 좋을 것 같아요. 일단 제가 생각해 놓은 건 조회 기능에 경우에는 E2E 테스트만 작성해도 충분한 것 같아요. 데이터 변경이 일어나는 기능은 E2E, 서비스, 도메인 테스트 정도 진행하면 어떨까 생각합니다.
> [FEAT] 리그 전체 조회 및 리그 스포츠 조회 기능 구현

- src/main/java/com/sports/server/game/application/GameService.java
- src/main/java/com/sports/server/game/application/GameServiceUtils.java
- src/main/java/com/sports/server/game/application/GameTeamService.java
- src/main/java/com/sports/server/game/domain/GameTeamRepository.java
- src/main/java/com/sports/server/game/dto/request/GameTeamCheerRequestDto.java
- src/main/java/com/sports/server/game/exception/GameErrorMessages.java
- src/main/java/com/sports/server/game/exception/GameExceptionMessages.java
- src/main/java/com/sports/server/game/presentation/GameController.java
- src/test/java/com/sports/server/game/acceptance/GameTeamAcceptanceTest.java
- src/test/java/com/sports/server/game/application/GameTeamServiceTest.java
- src/test/resources/game-fixture.sql
- closed #47 
- 두개 이상의 도메인에서 호출하는 Game 을 찾는 메서드를 GameServiceUtils 로 분리
- 응원 요청을 받고 횟수를 증가시키는 기능 구현
- 경기 횟수 증가 확인 테스트 구현
- GameController 에서 GameTeamController 를 분리하지 않은 이유
제 생각에는 Game이 무조건 GameTeam 의 진입점이기에 외부로 향하는 프레젠테이션 계층인 controller 의 경우에는 gameId 를 필수적으로 통해서만 gameTeam 로직으로 이동할 수 있어서 굳이 분리시키지 않았습니다. 이에 대한 의견이 궁금해요!
- GameService 와 GameTeamService 를 분리한 이유
진입점이 Game 으로 고정된 것은 엔드포인트 상으로 진입할 때만 gameId 가 필요한 것이고, game 을 조회한 이후에 해당 경기에 속하는 team 과 관련된 로직을 gameService 에 두게 되는 것은 너무 클래스가 커질 것으로 우려했습니다. 또한, 경기의 팀과 관련된 로직이 계속해서 증가할 것을 예상했습니다. 이에 대해서도 의견 주세요!
- 테스트 코드 관련
- 처음으로 테스트를 작성하는 거라 이상할 수도 있는데 편하게 의견 주시면 고쳐보겠습니답 ! 🫡
- @Modifying 관련
- 응원 횟수 증가 쿼리 이후 영속성 컨텍스트를 초기화해야 할까요? 어차피 업데이트한 이후에는 쿼리가 다시 나가니까 상관없을 것이라고 생각했는데 제가 잘못 생각했으면 알려주세요!
> [FEAT] 응원하기 기능 구현

- src/main/java/com/sports/server/game/application/GameTeamPlayerService.java
- src/main/java/com/sports/server/game/domain/GameTeamPlayerRepository.java
- src/main/java/com/sports/server/game/dto/response/GameLineupResponse.java
- src/main/java/com/sports/server/game/presentation/GameController.java
- src/main/java/com/sports/server/team/domain/TeamPlayer.java
- src/main/resources/db/migration/V3__add-team-player.sql
- src/test/java/com/sports/server/game/acceptance/GameTeamPlayerAcceptanceTest.java
- src/test/resources/game-fixture.sql
closed #57 
closed #58 
- game_id로 전체 GameTeam의 플레이어들을 조회하는식으로 구현했어요.
- 하나의 GameTeam 당으로 조회하려다가 응원하기 조회도 한 번에 조회하고 있길래 라인업도 한 번에 불러오도록 짰습니다.
- 일단 `GameTeamPlayerService`와 `GameTeamPlayerRepository`를 만들어서 구현했습니다. 조회 로직 분리는 나중에 진행하려구요!
``` json
[
{
"gameTeamId": 6,
"teamName": "...",
"gameTeamPlayers": [
{"playerName": "...선수", "description": "..."}, 
{"playerName": "...선수", "description": "..."}, 
{"playerName": "...선수", "description": "..."}
]
},
{
"gameTeamId": 7,
"teamName": "...",
"gameTeamPlayers": [
{"playerName": "...선수", "description": "..."}, 
{"playerName": "...선수", "description": "..."}, 
{"playerName": "...선수", "description": "..."}
]
}
]
```
``` sql 
CREATE TABLE team_players
(
id            BIGINT AUTO_INCREMENT NOT NULL,
team_id       BIGINT                NOT NULL,
name …
```
> [FEAT] 라인업 조회 기능 추가 및 TeamPlayer 추가

- src/main/java/com/sports/server/game/application/GameService.java
- src/main/java/com/sports/server/game/dto/response/GameDetailResponse.java
- src/main/java/com/sports/server/game/dto/response/VideoResponse.java
- src/main/java/com/sports/server/game/presentation/GameController.java
- src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
- src/test/resources/game-fixture.sql
closed #66 
closed #67 
- 비디오 조회 API 구현
- 게임 상세 조회에서 스포츠 이름 추가
> [FEAT] 비디오 ID 조회 API 구현 및 게임 상세 조회에 스포츠 이름 추가

- src/main/java/com/sports/server/comment/infra/CommentDynamicRepositoryImpl.java
- src/test/java/com/sports/server/comment/acceptance/CommentAcceptanceTest.java
closed #73 
- 댓글 정렬 기준 수정
원래 의도는 최신순부터 조회하는 것은 맞으나 최신 -> 오래된 정렬이 아래에서 위로 올라가는 방향으로 정렬되어야 합니다. 하지만 지금 반대로 되어 있습니다. 
DB에서 정렬하고 커서페이징 하는 방향과 UI에서 보여주는 정렬 방향이 반대라 헷갈린 것 같습니다. 로직을 다음과 같이 수정했습니다.
``` java
@Override
public List<Comment> findByGameIdOrderByStartTime(Long gameId, Long cursor, Integer size) {
DynamicBooleanBuilder booleanBuilder = DynamicBooleanBuilder.builder();
return queryFactory.selectFrom(comment)
.join(gameTeam).on(comment.gameTeamId.eq(gameTeam.id))
.where(gameTeam.game.id.eq(gameId))
.where(booleanBuilder
.and(() -> comment.createdAt.goe(getCursorCreatedAt(cursor)))
.and(() -> comment.id.gt(cursor))
.build()
)
.orderBy(comment.createdAt.asc(), comment.id.asc())
.limit(size)
.fetch();
}
```
``` java
@Override
public List<Comment> findByGameIdOrderByStartTime(Long gameId, …
```
> [FIX] 댓글 조회 순서 로직 수정 #73

- src/main/java/com/sports/server/common/config/WebConfig.java
- src/main/resources/application-local.yml
- cors 허용 origins을 내부 하드 코딩이 아닌 application.yml로 분리
- application-local.yml에는 localhost:3000만 허용
- application-prod.yml에 실제 프론트 origin 설정
- origin을 외부 설정 파일로 분리함으로써 origin이 변경될 때마다 server 레포지토리를 커밋 하고 PR을 날릴 필요가 없습니다.
- be-config에서 prod.yml 파일을 수정 후 재배포만 하면 됩니다.
- be-config 레포지토리에 운영 환경 origin을 설정해두었습니다
> [CHORE] cors 허용 origin 외부 설정 파일로 분리

- src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
- src/test/java/com/sports/server/game/application/GameServiceTest.java
- closed #80 
- id 가 커서보다 크지 않은 경우에도 조회를 해야 하기에 로직을 수정한다.
- id 가 cursor보다 작고 시작 시간이 더 빠를 가능성이 있다. 
- test 를 추가했습니다!
> [FIX] 경기 전체 조회 시 페이징이 올바르지 않게 되는 오류를 해결한다

- src/main/java/com/sports/server/game/infra/GameDynamicRepositoryImpl.java
- src/test/java/com/sports/server/game/acceptance/GameAcceptanceTest.java
- src/test/java/com/sports/server/game/application/GameServiceTest.java
- closed #82 
- 페이징 되지 않도록 임시로 수정해뒀습니다!
- 종료된 경기들에 대해서는 날짜 기준으로 역정렬 해서 가장 최근의 경기부터 확인할 수 있도록 했습니다.
- 테스트는 우선 수정하지 않았습니다 -> 어차피 틀린 로직이기에..!
> [FIX] 임시로 페이징 되지 않도록 수정 및 경기 종료 시 정렬 기준 수정

- .github/workflows/ci.yml
- build.gradle
- src/main/resources/application-ci.yml
- src/main/resources/application.yaml
- src/test/java/com/sports/server/support/isolation/DatabaseManager.java
closed #95 
- TestContainer 의존성을 추가
- active profile이 local일 때는 h2로 테스트가 돌고 ci일 때는 도커 컨테이너로 mysql을 구동시켜서 테스트를 진행
- PR을 날리면 `active profile = ci` 환경에서 테스트가 돌면서 mysql 환경 테스트를 수행
- 평소 로컬에서 개발할 때는 h2 테스트 수행
사실 TestContainer를 사용하면 MySQL 컨테이너가 자동으로 구동되어 MySQL DB를 세팅해주기 때문에 로컬에서도 사용할 수 있습니다. 하지만 로컬 테스트에 적용할 때 아래와 같은 단점이 존재합니다.
- 도커를 켜야 한다.
- 테스트 속도가 느리다.
도커를 띄어서 테스트를 진행하게 되면 제 맥북 기준 12초가 걸리고 H2를 사용할 때는 2초밖에 안 걸립니다. 전체 테스트를 돌릴 경우가 많을텐데 매번 12초 이상 걸린다면 답답할 거라 생각해요. (인텔리제이에서 표시해주는 시간만 12초이지 실제 시간은 더 걸립니다. 스프링 컨텍스트를 띄우는 중에는 시간이 측정 안되기 때문에..)
그래서 로컬에서 개발할 때는 H2 데이터베이스를 사용해서 빠른 테스트 속도를 누리도록 했습니다. 단 MySQL 테스트가 최소 한 번 이상은 필요하기 때문에 필요할 때 application.yml에 profile을 `ci`로 변경하면 MySQL 테스트를 진행할 수 있습니다.
MySQL 테스트를 안하고 머지하는 휴먼 에러를 방지하기 위해 ci.yml을 추가했습니다. 기능 개발이 완료되고 PR을 날리게 되면 깃헙 액션에서 mysql 테스트를 대신 진행합니다. 테스트가 …
> [TEST] MySQL 테스트 환경 구축

- src/main/java/com/sports/server/query/repository/GamesQueryConditionMapper.java
- closed #100 
기존에 스트링 concat을 기준으로 정렬 및 커서 페이징을 수행했던 것을 순수하게 and, or 조건 쿼리로 개선했습니다.
아래 처럼 `BooleanBuilder`의 `and()` 메서드 하나에 조건들을 넣으면 괄호를 씌울 수 있는 것을 확인해서 개선해보았습니다.
``` java
DynamicBooleanBuilder booleanBuilder = DynamicBooleanBuilder.builder()
.and(() -> game.league.id.eq(gamesQueryRequestDto.getLeagueId()))
.and(() -> game.state.eq(state))
.and(() -> game.sport.id.in(gamesQueryRequestDto.getSportIds()));
if (state == GameState.FINISHED) {
return booleanBuilder
.and(() -> game.startTime.eq(cursorStartTime).and(game.id.lt(cursor))
.or(game.startTime.lt(cursorStartTime)))
.build();
}
```
테스트는 전부 통과합니다
- 이 PR이 머지되면 개선된 쿼리를 대상으로 어떻게 인덱스를 넣으면 좋을지 성능 테스트를 해볼 생각입니다.
> [REFACTOR] 게임 목록 조회 커서 페이징 쿼리 개선 #100

- src/docs/asciidoc/api.adoc
- src/main/java/com/sports/server/query/application/SportQueryService.java
- src/main/java/com/sports/server/query/dto/response/SportResponse.java
- src/main/java/com/sports/server/query/presentation/SportQueryController.java
- src/main/java/com/sports/server/query/repository/SportQueryRepository.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/command/cheertalk/presentation/CheerTalkControllerTest.java
- src/test/java/com/sports/server/command/game/presentation/GameControllerTest.java
- src/test/java/com/sports/server/command/report/presentation/ReportControllerTest.java
- src/test/java/com/sports/server/query/acceptance/SportQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/presentation/CheerTalkQueryControllerTest.java
- src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- src/test/java/com/sports/server/query/presentation/SportQueryControllerTest.java
- src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
- src/test/java/com/sports/server/support/DocumentationTest.java
- src/test/java/com/sports/server/support/RestDocsConfig.java
- closed #102 
- 스포츠 종목 전체 조회 기능 구현
- 도메인 용어 통일 필요하다고 생각
- 종목 / 스포츠 / 스포츠 종목 / 대회 종목..
- 문서화 테스트까지 작성했는데, 뭐가 문제인지 테스트 부분 롤백해보고,  새로 클론 받아서 main 브랜치 build 를 해봐도 스니펫이 일부만 생성되네요.. 짚이는 구석이 없어서 문제 해결 못하고 우선 pr 올립니당..
> [FEAT] 스포츠 전체 조회 기능 구현

- .github/workflows/ci.yml
- src/docs/asciidoc/api.adoc
- src/main/java/com/sports/server/command/league/domain/League.java
- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueResponse.java
- src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
- src/main/java/com/sports/server/query/repository/LeagueQueryDynamicRepository.java
- src/main/java/com/sports/server/query/repository/LeagueQueryDynamicRepositoryImpl.java
- src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
- src/main/resources/db/migration/V7__league-round.sql
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- src/test/resources/league-fixture.sql
-  closed #108 
- 연도별 필터링 기능 추가
- 응답 본문에 라운드 정보 추가
기능 구현 외에 PR 시 깃허브 액션에서 CI 과정을 진행 시 build 명령어가 아닌 test 명령어를 통해 테스트만 확인하도록 변경했습니다. 이유는 속도가 build 보다 test가 빠르고 mysql 환경에서 테스트가 다 도는지 확인이 필요한 것이기에 build까지는 필요없다고 생각해서입니다
> [FEAT] 리그 조회 시 연도 별 필터링 기능 추가

- src/main/java/com/sports/server/query/application/InProgressLeagueChecker.java
- src/main/java/com/sports/server/query/dto/response/LeagueResponse.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/query/application/InProgressLeagueCheckerTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- closed #113 
- 리그 조회 api 응답에 `isInProgress` 응답 추가
현재 진행 여부 판단 로직을 제 3의 클래스에게 위임했습니다.
``` java 
public class InProgressLeagueChecker {
public static boolean check(LocalDate today, League league) {
LocalDate startAt = league.getStartAt().toLocalDate();
LocalDate endAt = league.getEndAt().toLocalDate();
return (today.isEqual(startAt) || today.isAfter(startAt))
&& (today.isBefore(endAt)) || today.isEqual(endAt);
}
}
```
또 다른 방법으로는 `League` 도메인에게 로직을 위임하면 클래스 추가 없이 더 깔끔하게 구현할 수 있습니다.
``` java
public class League extends BaseEntity<League> {
// ...
@Column(name = "start_at", nullable = false)
private LocalDateTime startAt;
@Column(name = "end_at", nullable = false)
private LocalDateTime endAt;
///...
public boolean isInProgress(LocalDate today) {
LocalDate startDate = startAt.toLocalDate(); …
```
> [FEAT] 리그 조회 시 진행 중 여부 추가

- src/main/java/com/sports/server/query/dto/mapper/RecordMapper.java
- src/main/java/com/sports/server/query/dto/response/RecordResponse.java
- src/main/java/com/sports/server/query/dto/response/ReplacementRecordResponse.java
- src/main/java/com/sports/server/query/dto/response/ScoreRecordResponse.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/presentation/TimelineQueryControllerTest.java
- closed #121 
- 타임라인 조회에 게임팀 ID 추가 (클라이언트의 요구)
- Record 응답에 ID 추가 (매니저 서버의 요구)
> [FEAT] 타임라인 조회에 필드 추가

- src/main/java/com/sports/server/ServerApplication.java
- src/main/resources/logback-spring.xml
- closed #123
- 디폴트 타임존을 Asia/Seoul로 변경
- 관객 서버 타임존을 변경했는데도 뭔가 시간이 이상하다면 RDS나 매니저 서버도 확인해봐야 할 듯?
> [FIX] 서버 시간 Asia/Seoul로 변경

- src/main/java/com/sports/server/query/dto/response/GameResponseDto.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/query/acceptance/CheerTalkQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/acceptance/GameQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/presentation/GameQueryControllerTest.java
- closed #131 
- 게임 전체 조회 시 video id 도 함께 반환하도록 수정
- 저번 이슈 관련 pr 머지한 뒤로 #125 계속 테스트 통과를 못하고 오류가 나는데 (현재 main 에도 빌드 실패로 떠 있네요) 로컬에서는 문제가 없어서요.. 배포 환경에서 문제가 있는 것 같은데 해결 방법을 모르겠네요 ㅠ 또 시간 관련 문제인 것 같아요
> [ADD] 게임 전체 조회 시 영상 관련 컬럼 추가

- src/docs/asciidoc/api.adoc
- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueDetailResponse.java
- src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
- src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- closed #137 
- 리그 단건 조회 기능 구현
- 프론트에서 리그의 라운드를 조회하는 기능이 필요하다 하여 추가
- 라운드만 가져올 바에 차라리 단건 조회 만들기로 결정
**빠른 기능 반영을 위해 코드 리뷰 없이 머지하겠습니다!**
> [FEAT] 리그 단건 조회 기능 구현

- src/main/java/com/sports/server/query/repository/ScoreRecordQueryRepository.java
- src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
- src/test/resources/record-fixture.sql
- #139 
아래 보면 점수 스냅샷이 이상합니다. 원인을 뜯어보니 점수 기록 계산 시 `score_record`를 `recorded_at`으로 정렬해서 계산했습니다. 이렇게 되면 아래처럼 후반전 6분이 전반전 15분보다 먼저 계산되어 점수 기록이 꼬이게 됩니다.
`score_record` 조회 시 `record_id`로 정렬하도록 수정하고 테스트도 이를 고려하도록 수정했습니다!
``` java
@Query("select sr from ScoreRecord sr " +
"join fetch sr.record r " +
"join fetch r.gameTeam gt " +
"join fetch gt.leagueTeam lt " +
"join fetch r.recordedQuarter rq " +
"join fetch sr.lineupPlayer srp " +
"where r.game.id = :gameId " +
"order by r.id asc")
List<ScoreRecord> findByGameId(@Param("gameId") Long gameId);
```
> [FIX] ScoreRecord 조회 시 recorded_at이 아닌 id로 정렬하도록 수정 #139

- src/main/java/com/sports/server/command/game/application/GameTeamService.java
- src/main/java/com/sports/server/command/game/domain/GameTeam.java
- src/test/java/com/sports/server/command/game/application/GameLeagueTeamServiceTest.java
- closed #141 
- 응원 횟수 제한
- 총 응원 횟수 제한
> [FIX] 한 번에 보낼 수 있는 응원 횟수 제한 로직 구현

- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueTeamPlayerResponse.java
- src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
- src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
- src/main/java/com/sports/server/query/repository/LeagueTeamPlayerQueryRepository.java
- src/main/java/com/sports/server/query/repository/LeagueTeamQueryRepository.java
- src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- src/test/resources/league-fixture.sql
* closed #147
* 대회팀과 대회 팀 선수가 가나다 순으로 조회되도록 변경
* 해당 인수 및 문서화 테스트 작성
> [REFACTOR] 대회팀, 대회팀 선수 가나다 순으로 뜨도록 수정

- src/main/java/com/sports/server/auth/filter/JwtAuthorizationFilter.java
- src/test/java/com/sports/server/auth/acceptance/AuthAcceptanceTest.java
- closed #171 
`jwtFilter`에서 쿠키의 토큰이 만료된 경우 예외를 터뜨리지 않도록 변경했습니다. 예외를 터뜨리지 않아도 `Authentication`을 `SecurityContextHolder`에 세팅하지 않기 때문에 토큰이 필요한 요청에선 시큐리티가 예외를 터뜨립니다.
대신 예외를 터뜨리지 않음으로써 로그인이 필요 없는 요청에 토큰이 이상하다고 401을 던지지 않게 됩니다.
``` java
private void authenticate(Cookie cookie) {
String accessToken = cookie.getValue();
try {
jwtUtil.validateToken(accessToken);
} catch (UnauthorizedException e) {
return;
}
Authentication authentication = new UsernamePasswordAuthenticationToken(
jwtUtil.getEmail(accessToken),
null,
null
);
SecurityContextHolder.getContext().setAuthentication(authentication);
}
```
> [FIX] 만료된 토큰으로 로그인 요청 버그 해결

- src/docs/asciidoc/api.adoc
- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueTeamDetailResponse.java
- src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/query/acceptance/LeagueQueryAcceptanceTest.java
- src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- closed #184 
- 리그팀 상세 조회
- 위와 같이 리그팀 정보를 수정할 때 필요한 상세 정보 조회를 구현했습니다! 화면에 맞게 잘 설계됐는지 확인 부탁드려요 👀
- 기존에 있던 com.sports.server.query.dto.response의 LineupPlayerResponse 를 사용할까 하다가 LeagueDetailResponse 내부에 따로 LineupPlayerResponse 를 만들어 사용했습니다. 어떤 방향이 더 나을지 피드백 주세욥!
> [FEAT] 리그팀 상세 조회

- src/main/java/com/sports/server/command/game/application/LineupPlayerService.java
- src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
- src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
- src/main/resources/db/migration/V17__update-lineup-players.sql
- src/test/java/com/sports/server/command/timeline/TimelineFixtureRepository.java
- src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
- src/test/resources/game-fixture.sql
- src/test/resources/timeline-fixture.sql
- closed #212 
- 출전 정보를 의미하는 is_playing 필드 추가
- 기존에 데이터베이스에 있던 값들은 모두 true로
- 이유 : 기존에는 출전 / 선발 / 후보를 구분하지 않고 뛰고 있는 사람만 라인업에 올렸기 때문에
- 기본값은 false 로 생성되도록
- 교체 타임라인 등록 시 선수의 출전 정보 변경
- 선발 / 후보 변경 시에 선수의 출전 정보 변경
기존에는 출전 / 선발 / 후보를 구분하지 않고 뛰고 있는 사람만 라인업에 올렸기 때문에 기존 데이터베이스에 있던 라인업 선수들은 모두 is_playing 을 true 로 갖게 하도록 했는데 어떻게 생각하시는지?
슬랙에 코멘트 남긴 것처럼 선수의 출전 정보를 저장하는 시점이 두개가 있다고 생각했어
1-1. 라인업 선수가 선발이 될 때마다 isPlaying 을  true 로 바꾸고 후보가 될 때마다 false 로 바꾼다. 그리고 교체 타임라인에서 선발이었던 선수가 나갈 때마다 false 로 바꾼다.
1-2. 게임이 시작하는 시점에 (게임 시작 상태변경 타임라인이 등록되는 경우) 라인업 선수 중 선발인 선수는 모두 isPlaying 을 true 로 바꾼다. 그리고 교체 타임라인에서 선발이었던 선수가 나갈 때마다 false 로 바꾼다.
이 pr 에서는 1-1 로 구현하기는 했어. 왜냐하면 1-2 의 경우에는 상태변경 타임라인이 등록되고 만약 롤백되는 상황이 일어나게 되면 변경 지점이 너무 많아져서 복잡해지지 않을까? 하는 생각이 들었어.
게임 시작 전까지는 사실상 출전 == 선발이니까 괜찮지 않을까? 하는 생각이었어
이거에 대해 어떻게 …
> [FEAT] 출전 선수 정보 변경

- src/main/java/com/sports/server/command/league/application/LeagueService.java
- src/main/java/com/sports/server/command/league/domain/Round.java
- src/main/java/com/sports/server/command/league/dto/LeagueRequestDto.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/command/league/acceptance/LeagueAcceptanceTest.java
- src/test/java/com/sports/server/command/league/presentation/LeagueControllerTest.java
- #222 
- 리그 생성 시 자동으로 매니저의 organization을 리그에 등록. organization을 request로 보내지 않아도 되도록 수정
> [REFACTOR] 리그 생성 시 자동으로 Organization 등록되도록 수정

- src/main/java/com/sports/server/command/game/domain/Game.java
- src/main/java/com/sports/server/command/timeline/domain/GameProgressTimeline.java
- src/main/java/com/sports/server/command/timeline/domain/GameProgressType.java
- src/main/java/com/sports/server/command/timeline/domain/PKTimeline.java
- src/main/java/com/sports/server/command/timeline/domain/ReplacementTimeline.java
- src/main/java/com/sports/server/command/timeline/domain/ScoreTimeline.java
- src/main/java/com/sports/server/command/timeline/domain/Timeline.java
- src/test/java/com/sports/server/command/timeline/domain/GameProgressTimelineTest.java
- src/test/java/com/sports/server/query/acceptance/TimelineQueryAcceptanceTest.java
- src/test/resources/timeline-fixture.sql
- closed #269 
- progressType 에서 GAME_START 삭제
- 전반전 시작이 같은 기능을 하도록 수정
1. 전반전 시작 등록 시
- 경기 시작을 등록한 것과 같이 state 가 PLAYING 으로 업데이트
2. 전반전 시작 삭제 시
- 삭제하고자 하는 타임라인의 progressType 이 QUARTER_START 고 previous quarter 가 '시작전' 인 경우 state 를 SCHEDULED 로 업데이트
위 로직 맞는지 크로스 체크 부탁드려요!
> [FEAT] 경기 시작 대신 전반전 시작을 사용하도록 수정

- src/main/java/com/sports/server/command/game/domain/Game.java
- src/main/java/com/sports/server/command/timeline/application/TimelineService.java
- src/main/java/com/sports/server/command/timeline/exception/TimelineErrorMessage.java
- src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
- src/test/resources/timeline-fixture.sql
- closed #271 
- Game의 state가 FINISHED일 때 새로운 타임라인 등록 시도 시 에러 발생
> [FEAT] 경기 종료 이후 새로운 타임라인 등록 막기

- src/main/java/com/sports/server/command/game/application/GameService.java
- src/main/java/com/sports/server/command/league/domain/League.java
- src/main/java/com/sports/server/command/league/domain/Round.java
- src/main/java/com/sports/server/query/application/TimelineQueryService.java
- src/test/java/com/sports/server/command/game/application/GameServiceTest.java
- src/test/resources/timeline-fixture.sql
- closed #285 
- 게임 저장 / 수정 로직 일부 수정
- 테스트 추가
> [FEAT 리그의 maxRound 보다 등록하고자 하는 경기의 round 가 더 크면 등록하지 못하도록 막는다

- src/main/java/com/sports/server/ServerApplication.java
- src/main/java/com/sports/server/command/game/application/GameService.java
- src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
- src/main/java/com/sports/server/command/game/domain/GameRepository.java
- src/test/java/com/sports/server/command/game/application/GameServiceTest.java
- src/test/java/com/sports/server/support/fixture/GameFixtureRepository.java
- closed #249 
- 시작된지 5시간이 지난 경기는 매일 정각마다 경기의 상태를 종료로 변경한다.
- 스케줄러를 더 자세히 테스트할 수 있는 방향이 있을지 고민됩니당
> [FEAT] 게임 종료 스케줄링 추가

- src/main/resources/db/migration/dev/T1__init.sql
#320 
- 전체 스키마 구조 리팩토링
- https://dbdiagram.io/d/hufscheer_hyobin-67c29d62263d6cf9a0ddf09c (이전 erd)
- https://dbdiagram.io/d/hufscheer_new_erd-67c1ba97263d6cf9a0cf51f2 (new erd)
- 기존에 member_id와 administrator_id가 혼동 사용되어 administrator_id로 통일
> [REFACTOR] DB 스키마 구조 리팩토링

- src/main/java/com/sports/server/command/game/application/GameService.java
- src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
- src/main/java/com/sports/server/command/game/domain/Game.java
- src/main/java/com/sports/server/command/game/domain/GameResult.java
- src/main/java/com/sports/server/command/game/domain/GameTeam.java
- src/main/java/com/sports/server/command/game/exception/GameErrorMessages.java
- src/main/java/com/sports/server/command/league/application/LeagueStatisticsService.java
- src/main/java/com/sports/server/command/league/domain/League.java
- src/main/java/com/sports/server/command/league/domain/LeagueStatistics.java
- src/main/java/com/sports/server/command/league/domain/LeagueStatisticsRepository.java
- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueStatisticsResponse.java
- src/main/java/com/sports/server/query/dto/response/TeamResponse.java
- src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
- src/main/java/com/sports/server/query/repository/LeagueStatisticsQueryRepository.java
- src/main/java/com/sports/server/query/repository/LeagueTeamQueryRepository.java
- src/main/java/com/sports/server/query/repository/LegueStatisticsQueryRepository.java
- src/test/java/com/sports/server/command/game/application/GameServiceTest.java
- src/test/java/com/sports/server/command/league/application/LeagueStatisticsServiceTest.java
- src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- src/test/resources/league-fixture.sql
#328 
- 리그 통계 생성 구현 (결승전 종료 시 해당 팀 승자가 리그 우승자, 패자가 2위팀으로 자동으로 등록되게하고, 최다응원팀, 최다댓글팀도 등록 ) 및 테스트 코드 작성
- 리그 통계 쿼리 부분 구현 및 테스트 코드 작성
- 리그 fixture sql쿼리문 수정
- GameServiceTest 부분에서 스케줄러 작동 테스트하는 부분에 LeagueStatisticsService은 Mock Bean으로 넣었는데 괜찮을까요? 해당 서비스는 LeagueServiceTest에서 작동을 테스트하여서 목으로 넣었습니다
- 득점왕 리스트는 또 따로 화면이 있길래 다른 api로 빼겠습니다
> [Feature] 리그 통계 api 및 테스트 코드 구현

- src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
- src/main/java/com/sports/server/command/league/application/LeagueStatisticsService.java
- src/main/java/com/sports/server/command/league/application/LeagueTopScorerService.java
- src/main/java/com/sports/server/command/league/domain/LeagueTeamRepository.java
- src/main/java/com/sports/server/command/league/domain/LeagueTopScorerRepository.java
- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueStatisticsResponse.java
- src/main/java/com/sports/server/query/dto/response/LeagueTeamResponse.java
- src/main/java/com/sports/server/query/dto/response/LeagueTopScorerResponse.java
- src/main/java/com/sports/server/query/presentation/LeagueQueryController.java
- src/main/java/com/sports/server/query/repository/TimelineQueryRepository.java
- src/main/java/com/sports/server/query/support/PlayerInfoProvider.java
- src/test/java/com/sports/server/command/league/application/LeagueStatisticsServiceTest.java
- src/test/java/com/sports/server/command/league/application/LeagueTopScorerServiceTest.java
- src/test/java/com/sports/server/query/presentation/LeagueQueryControllerTest.java
- src/test/resources/league-fixture.sql
#351
- 리그 통계, 득점왕 api 구현 및 테스트 작성
- 리그 득점왕도 리그 통계 업데이트되는 시점(결승전 종료)에 스케줄러가 자동으로 업데이트
- 1골 이상 득점한 선수만 포합합니다
- 해당 화면에서 연도별 리그 조회 api -> 해당 리그들 통계, 득점왕 조회  api   요 순서로 사용할 것 같네요
- 양방향 매핑 사용으로 N+1 나기는 하는데 팀 수가 많지는 않아서 성능에 문제가 생길 것 같진 않습니다. 그래도 뭔가 최적화와 편의성 사이에서 타협점을 잡는 것이 항상 고민이네요
- 스케줄러 작동은 데이터 넣고 QA 따로 해봐야할 것 같습니다
> [FEATURE] '이전 리그'에 필요한 리그 통계, 득점왕 구현

- src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
- src/test/resources/league-fixture.sql
#368 
1. 필터링_조건으로_리그를_조회한다(): 2025년도 리그 6개가 조회되는지 확인하고, 리그 이름에 "축구대회"가 포함되는지 검증
2. 리그_상세정보를_조회한다(): 리그 이름, 팀 수(3개), maxRound(8), inProgressRound(8) 등 구체적인 값들을 검증
3. 리그팀의_선수들을_조회한다(): 선수 수(2명)와 정확한 선수 이름들("진승희", "이동규")을 검증하되, 순서는 상관없도록containsExactlyInAnyOrder 사용
4. 리그의_상위_득점자를_조회한다():  1위 진승희(5골), 2위 이동규(3골) 확인
5. 연도별_상위_득점자를_조회한다(): 각 득점자의 이름과 득점수가 유효한지 검증
- 기존의 팀 조회 관련 부분들은 팀 api에 있길래 삭제했습니다
- assertThat(secondScorer.playerName()).isEqualTo("박주장") 와 같이 값 하드코딩해서 테스트하니까 sql문 바꾸면 테스트가 깨지더라고요.. SQL문에 맞춰서 테스트를 짜야하는 상황이라 조금 이상하네요. 이런 부분 때문에 전에 테스트 넣는 방식 바꾸고 싶어하셨던 것 같은데 운영하면서 바꿔봐도 좋을 것 같네요
> [TEST] 기존 오류 해결 및 새로 생긴 서비스 메소드 테스트 추가

- src/main/java/com/sports/server/command/cheertalk/domain/CheerTalkRepository.java
- src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
- src/main/java/com/sports/server/command/game/domain/GameTeamRepository.java
- src/main/java/com/sports/server/command/league/application/LeagueService.java
- src/main/java/com/sports/server/command/league/domain/LeagueTeamRepository.java
- src/main/java/com/sports/server/command/league/dto/LeagueTeamStats.java
- src/main/resources/static/docs/api.html
- src/test/java/com/sports/server/command/league/application/LeagueServiceTest.java
- src/test/resources/league-fixture.sql
#370 
- 리그 통계와 마찬가지로 결승전 종료 시에 집계하도록 구현했습니다.
- 테스트 메소드 내용은 아래와 같습니다
- 리그 1의 팀들이 올바르게 집계되는지 확인
- 팀1: 150 응원, 2 응원톡
- 팀2: 100 응원, 2 응원톡
- 팀3: 75 응원, 1 응원톡
- 팀4: 리그 2에서 총 30 응원수, 1 응원톡
- 팀5: 리그 2에서 총 0 응원수, 0 응원톡
- 기존 대회들 업데이트 하는 방식 같이 생각해봐요
> [FEATURE] TotalCheerCount, TotalTalkCount 자동 업데이트 로직 구현

- .github/workflows/cd.yml
- src/main/java/com/sports/server/command/league/domain/LeagueProgress.java
- src/main/java/com/sports/server/common/config/CloudWatchCustomConfig.java
- src/main/java/com/sports/server/query/application/LeagueProgressComparator.java
- src/main/java/com/sports/server/query/application/LeagueQueryService.java
- src/main/java/com/sports/server/query/application/TeamQueryService.java
- src/main/java/com/sports/server/query/dto/response/LeagueDetailResponse.java
- src/main/java/com/sports/server/query/dto/response/LeagueResponse.java
- src/main/java/com/sports/server/query/dto/response/LeagueResponseToManage.java
- src/main/java/com/sports/server/query/repository/GameQueryRepository.java
- src/main/java/com/sports/server/query/repository/LeagueQueryRepository.java
- src/main/java/com/sports/server/query/repository/TeamQueryRepository.java
- src/test/java/com/sports/server/command/league/domain/LeagueProgressTest.java
- src/test/java/com/sports/server/query/acceptance/CheerTalkEventHandlerTest.java
- src/test/java/com/sports/server/query/application/LeagueQueryServiceTest.java
- closed #389 
- `LeagueProgress` 의 우선순위가 Map 형태로 서비스 레이어에 존재 -> `LeagueProgress` 내부로 옮김
- `LeagueProgress` 의 우선순위에 따른 Map 을 통해 정렬 -> Comparator 따로 구현
- `https://www.hufscheer.com/leagues/165` 이 페이지에서의 로딩 속도가 너무 느려서 확인해보니, 호출하는 API 가 1.32s 가 걸리는 것을 확인
<br>
- k6 로 100번 쐈을 때에는 평균 약 3s 까지 걸리는 것을 확인
- N+1 문제가 발생하는 것을 확인해 in 절을 통해 쿼리 단축
> [REFACTOR] Comparator 구현 및 N+1 개선

- src/main/java/com/sports/server/query/repository/TimelineQueryRepository.java
- src/test/java/com/sports/server/command/league/application/LeagueTopScorerServiceTest.java
- src/test/java/com/sports/server/command/timeline/application/TimelineServiceTest.java
- src/test/resources/timeline-fixture.sql
#391 
- 레포지토리 메소드에 join 시 조건을 추가했습니다
- 테스트 코드에 다른 리그의 득점도 추가하여 검증했습니다
- 추가적으로 타임라인 fixture 변경으로 타임라인 갯수가 바뀌어도 '마지막_타임라인을_차례로_삭제한다' 메소드 실패하지 않도록 동적으로 타임라인 갯수 계산하도록 변경했습니다
> [FIX] 다른 리그에서의 득점은 포함하지 않도록 수정

- src/main/java/com/sports/server/command/game/application/GameService.java
- src/main/java/com/sports/server/command/game/application/GameStatusScheduler.java
- src/main/java/com/sports/server/command/game/domain/GameRepository.java
- src/main/java/com/sports/server/command/game/domain/LineupPlayer.java
- src/main/java/com/sports/server/command/game/presentation/GameController.java
- src/test/java/com/sports/server/support/DocumentationTest.java
#402
- 리그 통계 수동 업데이트 api 추가는 기존에 작업했던 거라 같이 올렸어요 양해좀..
- 선발 등록 관련 커밋은 두 번째 커밋만 봐도 될 듯
- 무서우면 오늘 경기 끝나고 머지하죠
> [Fix] 선발 등록 시 is_playing 1로 변경 + 리그 통계 수동 업데이트 api 추가
